theme: jekyll-theme-cayman

title: Artem Kalinovskiy

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: default
      permalink: /blog/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include: [_pages]
